### ISSUE TITLE
Create correct connection strings

### ISSUE THREAD

**Issue by Morten-Schultz-Nielsen** [AspIT-CV/Aspit.StudentReg#8]
The connection string we are using right now has a flaw:
1. The connection string only works from our computer

Problem with fixing this:
If we make the connection string work for other users then everyone on the internet has free access to the database (because the app.config is visible here on github which means they can easily find/get the connection string)

**Comment by MagnusBou** [comment]
I have added an issue, for creating a test database here #9

**Comment by MagnusBou** [comment]
To limit access to the connection string, we might try somthing like this.. https://stackoverflow.com/questions/45677569/how-do-i-keep-asp-net-connection-string-passwords-secure-on-a-git-repository

**Comment by Morten-Schultz-Nielsen** [comment]
Guess this is the best we can do it, but it comes with a problem: We will both have to create our own connection.config files then.

**Comment by MagnusBou** [comment]
Yes, that's right - But isn't the solution just to share the connection.config over email?

I am going to try making the code..

**Comment by Morten-Schultz-Nielsen** [comment]
Its a solution, its not a nice solution, but its a solution =b
Its ok with me.
